### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/tweepypoll#41]
<img width="744" alt="Screen Shot 2022-01-31 at 2 17 09 PM" src="https://user-images.githubusercontent.com/94651544/151882279-cc71decc-da99-4444-bc9d-045497a4e66c.png">

**Comment by xiangwxt** [comment]
For this `tweepypoll` package, we choose to go for a MIT license. The reasons are detailed in below:

- The core part of this python package is code. So that a software licence that is in common use is an easier choice for contributors and users of our package.
- We don't build our package in a community that has a preferred license. We can decide which license that's most suitable for our code, users and contributors without restriction on specific license to go with.
- We want our license to be simple and permissive, well known and commonly used in the python programming community. 
- The MIT license satisfy all the requirements and is a good fit for our package. 
  -  It's easy and simple as we only need to specify the year and authors for it to work for the package. 
  - It permits the use in commercial, distribution, modification, and private use, which covers all potential scenarios of the usage of our package. 
  - It's widely used and accepted in the python package development community.
